name: TESTRUNNER.CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Define SHORT_HASH Variable
      run: echo "::set-env name=SHORT_HASH::$(git rev-parse --short ${{github.sha}})"
    - name: Get BRANCH_NAME Variable
      uses: nelonoel/branch-name@v1
    - name: Check Out Current Branch
      uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore WebFormTest.sln
    - name: Define MSBUILD_PATH Variable
      run: echo "::set-env name=MSBUILD_PATH::C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"
    - name: Build with MSBuild
      run: |
        & "${{env.MSBUILD_PATH}}" WebApplication1\WebApplication1.vbproj -p:Configuration=Release
        & "${{env.MSBUILD_PATH}}" WebApplication1\WebApplication1.vbproj -p:DeployOnBuild=true -p:Configuration=Release -P:PublishProfile=FolderProfile.pubxml
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Test.Runner-${{env.SHORT_HASH}}
        path: .\WebApplication1\bin\Release
  
