name: TESTRUNNER.CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore WebFormTest.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild WebApplication1\WebApplication1.vbproj -p:DeployOnBuild=true -p:Configuration=Release -P:PublishProfile=FolderProfile.pubxml
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Test.Runner-$GITHUB_REF
        path: .\WebApplication1\bin\Release\Publish\
  
